/*CODE MAKTOUB ALA MYSQLWORKBENCH THABET FL SYNTAXE 9BAL MA TEKHDM*/
-- Créer l'utilisateur et attribuer les droits
CREATE USER 'TP3MI2'@'127.0.0.1' IDENTIFIED BY 'TP3MI2';
GRANT ALL PRIVILEGES ON *.* TO 'TP3MI2'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Utiliser la base de données (à créer si nécessaire)
CREATE DATABASE TP3_DB;
USE TP3_DB;

-- Créer les tables avec AUTO_INCREMENT
CREATE TABLE REGIONS (
    REGION_ID INT PRIMARY KEY AUTO_INCREMENT,
    REGION_NAME VARCHAR(50)
);

CREATE TABLE COUNTRIES (
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INT,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

CREATE TABLE LOCATIONS (
    LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
) ;

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_ID INT,
    LOCATION_ID INT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
) ;

-- Table JOBS
CREATE TABLE JOBS (
    JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(35) NOT NULL,
    MIN_SALARY DECIMAL(8,2),
    MAX_SALARY DECIMAL(8,2)
);

-- Table EMPLOYEES (avec clés étrangères)
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(25) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DECIMAL(8,2),
    COMMISSION_PCT DECIMAL(2,2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Table JOB_HISTORY (clé primaire composite)
CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID INT,
    START_DATE DATE,
    END_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE),  -- Clé composite
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);